# Generated by Django 2.1.7 on 2019-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployrecord',
            name='server_ids',
            field=models.CharField(default='', max_length=10, verbose_name='关联主机'),
        ),
        migrations.AlterField(
            model_name='deployrecord',
            name='status',
            field=models.CharField(default='', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_log_file',
            field=models.CharField(default='', max_length=150, verbose_name='日志文件'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_log_path',
            field=models.CharField(default='', max_length=150, verbose_name='日志目录'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_start',
            field=models.CharField(default='', max_length=100, verbose_name='启动脚本'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_stop',
            field=models.CharField(default='', max_length=100, verbose_name='停止脚本'),
        ),
        migrations.AlterField(
            model_name='project',
            name='excludes',
            field=models.TextField(default='', verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_task_status',
            field=models.CharField(default='', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='post_deploy',
            field=models.TextField(default='', verbose_name='deploy后置'),
        ),
        migrations.AlterField(
            model_name='project',
            name='post_release',
            field=models.TextField(default='', verbose_name='release后置'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prev_deploy',
            field=models.TextField(default='', verbose_name='deploy前置'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prev_release',
            field=models.TextField(default='', verbose_name='release前置'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_mode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='server_ids',
            field=models.CharField(default='', max_length=10, verbose_name='关联主机'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_envs',
            field=models.TextField(default='', verbose_name='全局变量'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_id',
            field=models.CharField(default='', max_length=100, verbose_name='关联用户id'),
        ),
    ]
