# Generated by Django 2.1.7 on 2019-05-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20190524_1104'),
        ('points', '0002_auto_20190516_1759'),
    ]

    operations = [
    ]
