# Generated by Django 2.1.7 on 2019-05-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20190527_1626'),
        ('points', '0004_auto_20190528_1032'),
    ]

    operations = [
    ]
