# Generated by Django 2.1.7 on 2019-05-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_merge_20190530_1018'),
    ]

    operations = [

    ]
