# Generated by Django 2.1.7 on 2019-05-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_remove_projectpoints_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpoints',
            name='link_id',
        ),
    ]
