# Generated by Django 2.1.7 on 2019-06-04 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0007_remove_projectpoints_link_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpoints',
            old_name='type_id',
            new_name='type',
        ),
    ]
