# Generated by Django 2.1.7 on 2019-06-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_points_pointsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpoints',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_points_role_id', to='rbac.Role', verbose_name='角色标识'),
        ),
    ]
