# Generated by Django 2.1.7 on 2019-06-11 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_auto_20190610_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='total_coins',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='米值'),
        ),
        migrations.AlterField(
            model_name='points',
            name='available_points',
            field=models.IntegerField(default=0, verbose_name='可用积分'),
        ),
        migrations.AlterField(
            model_name='points',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='总积分'),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户标识'),
        ),
        migrations.AlterField(
            model_name='pointsdetail',
            name='available_points',
            field=models.IntegerField(default=0, verbose_name='可用积分'),
        ),
        migrations.AlterField(
            model_name='pointsdetail',
            name='operation_points',
            field=models.IntegerField(default=0, verbose_name='本次操作的积分'),
        ),
        migrations.AlterField(
            model_name='pointsdetail',
            name='operation_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='pointsdetail',
            name='points_source',
            field=models.IntegerField(blank=True, null=True, verbose_name='积分来源'),
        ),
        migrations.AlterField(
            model_name='pointsdetail',
            name='points_status',
            field=models.IntegerField(default=1, verbose_name='积分状态'),
        ),
        migrations.AlterField(
            model_name='pointsdetail',
            name='points_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='积分类型'),
        ),
        migrations.AlterField(
            model_name='pointsdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户标识'),
        ),
    ]
