# Generated by Django 2.1.7 on 2019-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_projectpoints_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsdetail',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
    ]
