# Generated by Django 2.1.7 on 2019-06-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20190619_1742'),
        ('points', '0014_auto_20190611_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPointsEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('left_points', models.IntegerField(default=0, verbose_name='剩余积分')),
                ('project_receiver_percentage', models.IntegerField(default=0, verbose_name='项目负责人百分比')),
                ('project_sender_percentage', models.IntegerField(default=0, verbose_name='商务人员百分比')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_points_ex_project_id', to='business.Project', verbose_name='项目标识')),
            ],
            options={
                'verbose_name': '项目积分附加表',
                'verbose_name_plural': '项目积分附加表',
            },
        ),
    ]
