# Generated by Django 2.1.7 on 2019-05-24 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='task_design_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.TaskDesignType', verbose_name='任务设计方式标识'),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.TaskType', verbose_name='任务类型标识'),
        ),
        migrations.AddField(
            model_name='taskquality',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AddField(
            model_name='taskdesigntype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AddField(
            model_name='taskdesigntype',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.TaskType', verbose_name='任务类型标识'),
        ),
        migrations.AddField(
            model_name='taskassessment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AddField(
            model_name='skill',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.TaskType', verbose_name='技能标识'),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户标识'),
        ),
        migrations.AddField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户标识'),
        ),
    ]
