# Generated by Django 2.1.7 on 2019-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20190524_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='状态描述'),
        ),
    ]
