# Generated by Django 2.1.7 on 2019-05-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20190516_1759'),
        ('configuration', '0003_auto_20190524_1107'),
    ]

    operations = [
    ]
