# Generated by Django 2.1.7 on 2019-05-28 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_merge_20190528_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name='类型英文表示')),
                ('text', models.CharField(max_length=30, verbose_name='类型中文表示')),
            ],
            options={
                'verbose_name': '原因类型',
                'verbose_name_plural': '原因类型',
            },
        ),
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户标识'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.TaskType', verbose_name='技能标识'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户标识'),
        ),
        migrations.AlterField(
            model_name='taskassessment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AlterField(
            model_name='taskdesigntype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AlterField(
            model_name='taskdesigntype',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.TaskType', verbose_name='任务类型标识'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AlterField(
            model_name='taskquality',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='task_design_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.TaskDesignType', verbose_name='任务设计方式标识'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.TaskType', verbose_name='任务类型标识'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Company', verbose_name='公司标识'),
        ),
    ]
