# Generated by Django 2.1.7 on 2019-05-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20190527_1626'),
        ('configuration', '0005_auto_20190528_1032'),
    ]

    operations = [
    ]
