# Generated by Django 2.1.7 on 2019-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='average_salary',
            field=models.IntegerField(default=0, verbose_name='平均工资'),
        ),
    ]
