# Generated by Django 2.1.7 on 2019-06-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_tasktype_average_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskassessment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='taskdesigntype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='taskpriority',
            name='company',
        ),
        migrations.RemoveField(
            model_name='taskquality',
            name='company',
        ),
        migrations.RemoveField(
            model_name='taskstep',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='company',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
