# Generated by Django 2.1.7 on 2019-06-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20190613_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassessment',
            name='is_active',
            field=models.IntegerField(default=1, verbose_name='是否激活'),
        ),
    ]
