# Generated by Django 2.1.7 on 2019-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_auto_20190628_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdesigntype',
            name='is_active',
            field=models.IntegerField(default=1, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='is_active',
            field=models.IntegerField(default=1, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='is_active',
            field=models.IntegerField(default=1, verbose_name='是否激活'),
        ),
    ]
