# Generated by Django 2.1.7 on 2019-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_auto_20190628_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='desc',
            field=models.CharField(default='', max_length=50, verbose_name='状态描述'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='desc',
            field=models.CharField(default='', max_length=50, verbose_name='状态描述'),
        ),
    ]
