# Generated by Django 2.1.7 on 2019-05-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
    ]
