# Generated by Django 2.1.7 on 2019-05-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190524_1104'),
    ]

    operations = [
    ]
