# Generated by Django 2.1.7 on 2019-05-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_project_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='delete_time',
        ),
        migrations.AlterField(
            model_name='project',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
