# Generated by Django 2.1.7 on 2019-05-16 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190516_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核员'),
        ),
        migrations.AlterField(
            model_name='step',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
        migrations.AlterField(
            model_name='step',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_sender', to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
    ]
