# Generated by Django 2.1.7 on 2019-05-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20190516_1807'),
        ('business', '0003_remove_step_receive_status'),
    ]

    operations = [
    ]
