# Generated by Django 2.1.7 on 2019-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20190528_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='link_id',
            field=models.IntegerField(default=1, verbose_name='关链标识'),
        ),
    ]
