# Generated by Django 2.1.7 on 2019-05-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20190528_1049'),
        ('business', '0005_auto_20190527_1626'),
    ]

    operations = [
    ]
