# Generated by Django 2.1.7 on 2019-05-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_merge_20190530_1017'),
    ]

    operations = [

    ]
