# Generated by Django 2.1.7 on 2019-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20190530_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacklog',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='feedbacklog',
            name='linkid',
        ),
        migrations.RemoveField(
            model_name='files',
            name='task',
        ),
        migrations.RemoveField(
            model_name='step',
            name='receive_status',
        ),
        migrations.AddField(
            model_name='feedbacklog',
            name='step_log_file_id',
            field=models.IntegerField(default=0, verbose_name='步骤日志文件或富文本标识'),
        ),
    ]
