# Generated by Django 2.1.7 on 2019-06-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20190530_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstexts',
            name='tasklog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.TaskLog', verbose_name='任务日志标识'),
        ),
    ]
