# Generated by Django 2.1.7 on 2019-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20190606_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目完成时间'),
        ),
        migrations.AlterField(
            model_name='step',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
    ]
