# Generated by Django 2.1.7 on 2019-06-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20190606_1027'),
        ('business', '0011_auto_20190606_1057'),
    ]

    operations = [
    ]
