# Generated by Django 2.1.7 on 2019-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_merge_20190606_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.IntegerField(default=0, verbose_name='是否已发布'),
        ),
        migrations.AddField(
            model_name='task',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目完成时间'),
        ),
        migrations.AlterField(
            model_name='step',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
    ]
