# Generated by Django 2.1.7 on 2019-06-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20190611_1638'),
        ('business', '0013_auto_20190610_1244'),
    ]

    operations = [
    ]
