# Generated by Django 2.1.7 on 2019-06-13 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0014_merge_20190613_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_superior', to=settings.AUTH_USER_MODEL, verbose_name='上级主管'),
        ),
    ]
