# Generated by Django 2.1.7 on 2019-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20190619_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='path_thumb_w200',
            field=models.CharField(default='', max_length=300, verbose_name='宽度为 200 的缩略图文件路径（只针对图片）'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='path_thumb_w900',
            field=models.CharField(default='', max_length=300, verbose_name='宽度为 900 的缩略图文件路径（只针对图片）'),
        ),
        migrations.AlterField(
            model_name='files',
            name='path_thumb_w200',
            field=models.CharField(default='', max_length=300, verbose_name='宽度为 200 的缩略图文件路径（只针对图片）'),
        ),
        migrations.AlterField(
            model_name='files',
            name='path_thumb_w900',
            field=models.CharField(default='', max_length=300, verbose_name='宽度为 900 的缩略图文件路径（只针对图片）'),
        ),
    ]
