# Generated by Django 2.1.7 on 2019-06-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20190619_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steplog',
            name='memo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='备注'),
        ),
    ]
