# Generated by Django 2.1.7 on 2019-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20190625_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='', max_length=180, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(default='', max_length=80, verbose_name='类型'),
        ),
    ]
