# Generated by Django 2.1.7 on 2019-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_auto_20190629_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='任务评语'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='任务内容'),
        ),
    ]
