# Generated by Django 2.1.7 on 2019-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20190701_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(choices=[(0, '未开始'), (1, '已更新'), (2, '已反馈')], default=0, max_length=1),
        ),
    ]
