# Generated by Django 2.1.7 on 2019-07-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_task_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='label',
            field=models.SmallIntegerField(choices=[(0, '未开始'), (1, '已更新'), (2, '已反馈')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.SmallIntegerField(choices=[(0, '未开始'), (1, '已更新'), (2, '已反馈')], default=0),
        ),
    ]
