# Generated by Django 2.1.7 on 2019-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_feedbacklog_feedbacker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.CharField(default='', max_length=800, verbose_name='任务备注'),
        ),
    ]
