# Generated by Django 2.1.7 on 2019-07-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_auto_20190704_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=800, verbose_name='任务备注'),
        ),
    ]
