# Generated by Django 2.1.7 on 2019-05-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_merge_20190528_1025'),
        ('cmdb', '0003_merge_20190527_1622'),
    ]

    operations = [
    ]
