# Generated by Django 2.1.7 on 2019-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='base_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='工资'),
        ),
    ]
