# Generated by Django 2.1.7 on 2019-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20190613_1816'),
        ('rbac', '0002_userprofile_base_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='configuration.TaskType', verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='base_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='基本工资'),
        ),
    ]
