# Generated by Django 2.1.7 on 2019-06-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20190619_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='描述'),
        ),
    ]
