# Generated by Django 2.1.7 on 2019-07-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20190630_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar/image/default.png', upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='职位'),
        ),
    ]
